server:
  port: 8060
#  ssl:
#    key-store: classpath:mykey.jks
#    key-store-password: sBtX5A5R
#    key-store-type: JKS
#    key-alias: alias
spring:
  datasource:
    url: jdbc:mysql://117.50.57.86:3306/flytalk?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
    password: flyxia.cn
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  redis:
    # Redis服务器地址
    host: 117.50.57.86
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
#    password=
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: -1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 100


com:
  flyxia:
    exception:
      exception-maps: {2: 是我想要的错误,3: 是我想要的错误，错误码为3,500: 该用户不存在,
                      501: 查询参数非法,300: 电话号码不能为空,301: 注册失败,302: 电话号码已被注册,
                      401: 请输入用户名,402: 密码不能为空,403: 用户不存在,404: 用户密码错误,
                      2000: 验证码处理器不存在,2001: 验证码生成器不存在,
                      3000: 获取验证码的值失败,3001: 验证码的值不能为空,3002: 验证码不存在,
                      3003: 验证码已过期,3004: 验证码不匹配
                      }
    security:
      code:
        sms:
          length: 4
          expireIn: 300
  automannn:
    https: false

